#!/bin/sh
cat << "EOF"
                             ;\ 
                            |' \ 
         _                  ; : ; 
        / `-.              /: : | 
       |  ,-.`-.          ,': : | 
       \  :  `. `.       ,'-. : | 
        \ ;    ;  `-.__,'    `-.| 
         \ ;   ;  :::  ,::'`:.  `. 
          \ `-. :  `    :.    `.  \ 
           \   \    ,   ;   ,:    (\ 
            \   :., :.    ,'o)): ` `-. 
           ,/,' ;' ,::"'`.`---'   `.  `-._ 
         ,/  :  ; '"      `;'          ,--`. 
        ;/   :; ;             ,:'     (   ,:) 
          ,.,:.    ; ,:.,  ,-._ `.     \""'/ 
          '::'     `:'`  ,'(  \`._____.-'"' 
             ;,   ;  `.  `. `._`-.  \\ 
             ;:.  ;:       `-._`-.\  \`. 
              '`:. :        |' `. `\  ) \ 
      -hrr-      ` ;:       |    `--\__,' 
                   '`      ,' 
                        ,-' 

   
EOF

echo "Copy Skeleton"
cp -r /tmp/src/* /

aMem=$(free | awk '/^Mem:/{print $2}')
if (( aMem < 1999000 )); then
	echo "Less than 2GB memory on device, reducing squid guard checks"
	cp /tmp/src/etc/squidguard/squidGuard-light.conf /etc/squidguard/squidGuard.conf
	rm -rf /var/lib/squidguard/db/blacklists/ads/*
	rm -rf /var/lib/squidguard/db/blacklists/aggressive/*
	rm -rf /var/lib/squidguard/db/blacklists/audio-video/*
	rm -rf /var/lib/squidguard/db/blacklists/drugs/*
	rm -rf /var/lib/squidguard/db/blacklists/gambling/*
	rm -rf /var/lib/squidguard/db/blacklists/hacking/*
	rm -rf /var/lib/squidguard/db/blacklists/mail/*
	rm -rf /var/lib/squidguard/db/blacklists/spyware/*
	rm -rf /var/lib/squidguard/db/blacklists/suspect/*
	rm -rf /var/lib/squidguard/db/blacklists/warez/*
fi
echo "Generate squidguard databases"
/etc/cron.weekly/updateSquidGuard.sh

echo "Generate Squid certificates"
/usr/lib/squid/security_file_certgen -c -s /var/ssl_db -M 4mb

echo "Build & install Squidclam Antivirus"
cd /tmp
git clone https://github.com/SecuritasMachina/squidclamav
cd squidclamav
./configure --with-c-icap=/usr/include/c_icap
make
make install
if ((1<<32)); then
  	echo 64bits
  	libtool --finish /usr/lib/x86_64-linux-gnu/c_icap/
else
  	echo 32bits
	libtool --finish /usr/lib/arm-linux-gnueabihf/c_icap/
fi

echo "Copy c-icap config"
cp -r /tmp/src/etc/c-icap/* /etc/c-icap

echo "Apply permissions"
chmod ug+x /etc/cron.weekly/*
chmod ug+x /etc/cron.daily/*
chmod ug+x /etc/cron.hourly/*
chown -R proxy:proxy /var/log/squid
chown -R proxy:proxy /var/log/squidguard
chown -R proxy:proxy /var/ssl_db
chown -R proxy:proxy /var/lib/squid
chown -R proxy:proxy /etc/squid/ssl_cert
chmod ug+rwxt /var/log/squid
chmod ug+rwxt /var/log/squidguard
chmod ug+rw /var/log/squid/*
chmod ug+rw /var/log/squidguard/*
chmod ug+rw /var/ssl_db/*
chmod ug+rw /etc/squid/ssl_cert/*
chmod ug+rw /var/log/squid/*
chmod a+r /etc/issue
chmod a+x /usr/local/bin/*
chmod ug+x /usr/local/sbin/*

chmod ug+x /etc/cron.hourly/*
chmod ug+x /etc/cron.daily/*
chmod ug+x /etc/cron.weekly/*

chmod a+r /etc/issue
chown bind.bind /etchmod a+x /usr/local/bin/*
chmod ug+x /usr/local/sbin/*

chmod ug+x /etc/cron.hourly/*
chmod ug+x /etc/cron.daily/*
chmod ug+x /etc/cron.weekly/*

chmod a+r /etc/issue
chown bind.bind /etc/bind/named.conf.options
touch /var/log/querylog
chown bind.bind /var/log/querylog

#Harden
chmod ug-r /etc/squid/squid.conf

echo "Cleanup"
rm -rf /tmp/src