#!/bin/sh
cat << "EOF"
                             ;\ 
                            |' \ 
         _                  ; : ; 
        / `-.              /: : | 
       |  ,-.`-.          ,': : | 
       \  :  `. `.       ,'-. : | 
        \ ;    ;  `-.__,'    `-.| 
         \ ;   ;  :::  ,::'`:.  `. 
          \ `-. :  `    :.    `.  \ 
           \   \    ,   ;   ,:    (\ 
            \   :., :.    ,'o)): ` `-. 
           ,/,' ;' ,::"'`.`---'   `.  `-._ 
         ,/  :  ; '"      `;'          ,--`. 
        ;/   :; ;             ,:'     (   ,:) 
          ,.,:.    ; ,:.,  ,-._ `.     \""'/ 
          '::'     `:'`  ,'(  \`._____.-'"' 
             ;,   ;  `.  `. `._`-.  \\ 
             ;:.  ;:       `-._`-.\  \`. 
              '`:. :        |' `. `\  ) \ 
      -hrr-      ` ;:       |    `--\__,' 
                   '`      ,' 
                        ,-' 

   
EOF

cp -r /tmp/src/* /

echo "Generate squidguard databases"
#/etc/cron.daily/updateSquidGuard

echo "Generate Squid certificates"
/usr/lib/squid/security_file_certgen -c -s /var/ssl_db -M 4mb

echo "Build & install Squidclam Antivirus"
cd /tmp
git clone https://github.com/SecuritasMachina/squidclamav
cd squidclamav
./configure --with-c-icap=/usr/include/c_icap
make
make install
if ((1<<32)); then
  	echo 64bits
  	libtool --finish /usr/lib/x86_64-linux-gnu/c_icap/
else
  	echo 32bits
	libtool --finish /usr/lib/arm-linux-gnueabihf/c_icap/
fi

echo "Copy c-icap config"
cp -r /tmp/src/etc/c-icap/* /etc/c-icap

echo "Apply permissions"
chmod ug+x /etc/cron.weekly/*
chmod ug+x /etc/cron.daily/*
chmod ug+x /etc/cron.hourly/*

chown -R proxy:proxy /var/log/squid
chown -R proxy:proxy /var/log/squidguard
chown -R proxy:proxy /var/ssl_db
chown -R proxy:proxy /var/lib/squid
chown -R proxy:proxy /etc/squid/ssl_cert

chmod ug+rwxt /var/log/squid
chmod ug+rwxt /var/log/squidguard
chmod ug+rw /var/log/squid/*
chmod ug+rw /var/log/squidguard/*
chmod ug+rw /var/ssl_db/*
chmod ug+rw /etc/squid/ssl_cert/*
chmod ug+rw /var/log/squid/*
chmod a+r /etc/issue
#Harden
chmod ug-r /etc/squid/squid.conf

echo "Cleanup"
rm -rf /tmp/src