#!/bin/sh
cat << "EOF"
                             ;\ 
                            |' \ 
         _                  ; : ; 
        / `-.              /: : | 
       |  ,-.`-.          ,': : | 
       \  :  `. `.       ,'-. : | 
        \ ;    ;  `-.__,'    `-.| 
         \ ;   ;  :::  ,::'`:.  `. 
          \ `-. :  `    :.    `.  \ 
           \   \    ,   ;   ,:    (\ 
            \   :., :.    ,'o)): ` `-. 
           ,/,' ;' ,::"'`.`---'   `.  `-._ 
         ,/  :  ; '"      `;'          ,--`. 
        ;/   :; ;             ,:'     (   ,:) 
          ,.,:.    ; ,:.,  ,-._ `.     \""'/ 
          '::'     `:'`  ,'(  \`._____.-'"' 
             ;,   ;  `.  `. `._`-.  \\ 
             ;:.  ;:       `-._`-.\  \`. 
              '`:. :        |' `. `\  ) \ 
      -hrr-      ` ;:       |    `--\__,' 
                   '`      ,' 
                        ,-' 

   
EOF
echo "Harden & Enable ssh"
if cat /etc/ssh/sshd_config | grep "Port 20022" ; then
     echo "Port 20022 already exists"
else
	echo "Adding Port 20022, MaxAuthTries 6, MaxSessions 2"
	echo "Port 20022" >> /etc/ssh/sshd_config
	echo "MaxAuthTries 3" >> /etc/ssh/sshd_config
	echo "MaxSessions 5" >> /etc/ssh/sshd_config
	#echo "TCPKeepAlive no" >> /etc/ssh/sshd_config
	echo "AllowAgentForwarding no" >> /etc/ssh/sshd_config
	echo "AllowTcpForwarding no" >> /etc/ssh/sshd_config
	#echo "ClientAliveCountMax 2" >> /etc/ssh/sshd_config
	echo "Compression no" >> /etc/ssh/sshd_config
	echo "LogLevel verbose" >> /etc/ssh/sshd_config
	
	
fi
systemctl enable ssh
service ssh restart

echo "Echo reduce swapping"
sysctl vm.swappiness=20

cp -r /tmp/src/* /

aMem=$(free | awk '/^Mem:/{print $2}')
if (( aMem < 1999000 )); then
	echo "Less than 2GB memory on device, reducing squid guard checks"
	cp /tmp/src/etc/squidguard/squidGuard-light.conf /etc/squidguard/squidGuard.conf
	rm -rf /var/lib/squidguard/db/blacklists/ads/*
	rm -rf /var/lib/squidguard/db/blacklists/aggressive/*
	rm -rf /var/lib/squidguard/db/blacklists/audio-video/*
	rm -rf /var/lib/squidguard/db/blacklists/drugs/*
	rm -rf /var/lib/squidguard/db/blacklists/gambling/*
	rm -rf /var/lib/squidguard/db/blacklists/hacking/*
	rm -rf /var/lib/squidguard/db/blacklists/mail/*
	rm -rf /var/lib/squidguard/db/blacklists/spyware/*
	rm -rf /var/lib/squidguard/db/blacklists/suspect/*
	rm -rf /var/lib/squidguard/db/blacklists/warez/*
fi
echo "Generate squidguard databases"

/etc/cron.weekly/updateSquidGuard.sh

#sudo -u proxy squidGuard -C all

echo "Generate Squid certificates"
/usr/lib/squid/security_file_certgen -c -s /var/ssl_db -M 4mb

echo "Install Squidclam Antivirus"
cd /tmp
tar -xzf /tmp/include/squidclamav-7.1.tar.gz
cd squidclamav-7.1
./configure --with-c-icap=/usr/include/c_icap
make
make install

libtool --finish /usr/lib/arm-linux-gnueabihf/c_icap/
cp -r /tmp/src/etc/c-icap/* /etc/c-icap
echo "Configure lighttpd"
systemctl stop lighttpd.service
systemctl start lighttpd.service
systemctl enable lighttpd.service
lighttpd-enable-mod fastcgi
lighttpd-enable-mod fastcgi-php
service lighttpd restart

#Mimic RaspAP Config
mkdir -p /etc/raspap
cp /var/www/html/raspap.php /etc/raspap


echo "Apply permissions"
chmod o+x /etc/cron.weekly/*
chmod o+x /etc/cron.daily/*
chmod o+x /etc/cron.hourly/*
chown -R www-data /etc/raspap
chown -R www-data:www-data /var/www

chown -R proxy:proxy /var/ssl_db
chown -R proxy:proxy /var/lib/squid
chown -R proxy:proxy /etc/squid/ssl_cert
chmod go+rw /var/ssl_db/*
chmod go+rw /etc/squid/ssl_cert/*
chmod go+rw /var/log/squid/*
chmod a+r /etc/issue
#Harden
chmod go-r /etc/squid/squid.conf
tee -a /etc/sudoers << END
www-data ALL=(ALL) NOPASSWD:/sbin/ifdown
www-data ALL=(ALL) NOPASSWD:/sbin/ifup
www-data ALL=(ALL) NOPASSWD:/bin/cat /etc/wpa_supplicant/wpa_supplicant.conf
www-data ALL=(ALL) NOPASSWD:/bin/cat /etc/wpa_supplicant/wpa_supplicant-wlan[0-9].conf
www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/wifidata /etc/wpa_supplicant/wpa_supplicant.conf
www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/wifidata /etc/wpa_supplicant/wpa_supplicant-wlan[0-9].conf
www-data ALL=(ALL) NOPASSWD:/sbin/wpa_cli -i wlan[0-9] scan_results
www-data ALL=(ALL) NOPASSWD:/sbin/wpa_cli -i wlan[0-9] scan
www-data ALL=(ALL) NOPASSWD:/sbin/wpa_cli -i wlan[0-9] reconfigure
www-data ALL=(ALL) NOPASSWD:/sbin/wpa_cli -i wlan[0-9] select_network
www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/hostapddata /etc/hostapd/hostapd.conf
www-data ALL=(ALL) NOPASSWD:/bin/systemctl start hostapd.service
www-data ALL=(ALL) NOPASSWD:/bin/systemctl stop hostapd.service
www-data ALL=(ALL) NOPASSWD:/bin/systemctl start dnsmasq.service
www-data ALL=(ALL) NOPASSWD:/bin/systemctl stop dnsmasq.service
www-data ALL=(ALL) NOPASSWD:/bin/systemctl start openvpn-client@client
www-data ALL=(ALL) NOPASSWD:/bin/systemctl stop openvpn-client@client
www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/openvpn.ovpn /etc/openvpn/client/client.conf
www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/authdata /etc/openvpn/client/login.conf
www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/dnsmasqdata /etc/dnsmasq.conf
www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/dhcpddata /etc/dhcpcd.conf
www-data ALL=(ALL) NOPASSWD:/sbin/shutdown -h now
www-data ALL=(ALL) NOPASSWD:/sbin/reboot
www-data ALL=(ALL) NOPASSWD:/sbin/ip link set wlan[0-9] down
www-data ALL=(ALL) NOPASSWD:/sbin/ip link set wlan[0-9] up
www-data ALL=(ALL) NOPASSWD:/sbin/ip -s a f label wlan[0-9]
www-data ALL=(ALL) NOPASSWD:/bin/cp /etc/raspap/networking/dhcpcd.conf /etc/dhcpcd.conf
www-data ALL=(ALL) NOPASSWD:/etc/raspap/hostapd/enablelog.sh
www-data ALL=(ALL) NOPASSWD:/etc/raspap/hostapd/disablelog.sh
www-data ALL=(ALL) NOPASSWD:/etc/raspap/hostapd/servicestart.sh
www-data ALL=(ALL) NOPASSWD:/etc/raspap/lighttpd/configport.sh
www-data ALL=(ALL) NOPASSWD:/etc/raspap/openvpn/configauth.sh
END

echo "Cleanup"
rm -rf /tmp/src

