#!/bin/sh

### BEGIN INIT INFO
# Provides:        ntp
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start Reading Blacklists
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions


case $1 in
	start)
		log_daemon_msg "Generating BlackLists DB files" "proxy"
		sudo -u proxy squidGuard -C all &
  		;;
	stop)
		
		echo "Doesn't apply"
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "SquidGuard DB generator"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
