#!/bin/sh
cat << "EOF"
                             ;\ 
                            |' \ 
         _                  ; : ; 
        / `-.              /: : | 
       |  ,-.`-.          ,': : | 
       \  :  `. `.       ,'-. : | 
        \ ;    ;  `-.__,'    `-.| 
         \ ;   ;  :::  ,::'`:.  `. 
          \ `-. :  `    :.    `.  \ 
           \   \    ,   ;   ,:    (\ 
            \   :., :.    ,'o)): ` `-. 
           ,/,' ;' ,::"'`.`---'   `.  `-._ 
         ,/  :  ; '"      `;'          ,--`. 
        ;/   :; ;             ,:'     (   ,:) 
          ,.,:.    ; ,:.,  ,-._ `.     \""'/ 
          '::'     `:'`  ,'(  \`._____.-'"' 
             ;,   ;  `.  `. `._`-.  \\ 
             ;:.  ;:       `-._`-.\  \`. 
              '`:. :        |' `. `\  ) \ 
      -hrr-      ` ;:       |    `--\__,' 
                   '`      ,' 
                        ,-' 

   
EOF
#Add firewall modules
echo "Add IPTables Modules"
modprobe br_netfilter
modprobe ip_conntrack


#TODO Driver setup for Wintel & Realtek Chipset
#cd /usr/src/rtl8812au-5.1.5
#./dkms-install.sh

echo "Copy template files"
cp -ru /tmp/src/* /

echo "Add iptables rules"
iptables-restore < /etc/iptables.ipv4
ip6tables-restore < /etc/iptables.ipv6

echo "Setup WIFI Access Point"
if cat /etc/hostapd/hostapd.conf | grep "#wifi_random_added" ; then
	echo "Access Point name already generated - skipping"
else
	echo "Generate Random Access Point name"
	randomString=$(head /dev/urandom | tr -dc a-z0-9 | head -c 4 ; echo '')
	wifiAPName="SecureWall-$randomString"
	echo "Access point name is $wifiAPName"
	sed -i "s/SecureWall/$wifiAPName/g" /etc/hostapd/hostapd.conf
    echo "#wifi_random_added" >>/etc/hostapd/hostapd.conf

fi


echo "Disable dhcpcd for bridge"

if cat /etc/dhcpcd.conf | grep "denyinterfaces wlan0" ; then
     echo "denyinterfaces wlan0 already exists - step skipped"
else
	echo "Adding denyinterfaces wlan0"
	echo "denyinterfaces wlan0" >> /etc/dhcpcd.conf
fi

if cat /etc/dhcpcd.conf | grep "denyinterfaces eth0" ; then
     echo "denyinterfaces eth0 already exists - step skipped"
else
	echo "Adding denyinterfaces eth0"
	echo "denyinterfaces eth0" >> /etc/dhcpcd.conf
fi

service dhcpcd restart

systemctl unmask hostapd
service hostapd enable
service hostapd start
update-rc.d hostapd defaults

echo "Setup ip forwarding"
if cat /proc/sys/net/ipv4/ip_forward | grep "1" ; then
     echo "IP Forwarding already enabled - step skipped"
else
	echo "Enable packet forwarding for IPv4"
	echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
	
	echo "Enable packet forwarding for IPv6"
	echo "net.ipv6.conf.all.forwarding=1" >>/etc/sysctl.conf
	sysctl -w net.ipv4.ip_forward=1
	sysctl -w net.ipv6.conf.all.forwarding=1
	sysctl -w vm.swappiness=10
fi

echo "Restart networking"
/etc/init.d/networking restart

#echo "Setup docker container shared User and home dir"

#export CONTAINER_USER=shared
#export USER_PASSWORD=jaskS6jsdakashjsd!
#groupadd -g 1500 ${CONTAINER_USER} && \
#    useradd -r -u 1500 -g ${CONTAINER_USER} -G sudo ${CONTAINER_USER} \
#    -p "$(openssl passwd -1 $USER_PASSWORD)"
#mkdir /home/shared
#chown shared:shared /home/shared

echo "Check filesystem on each boot"
tune2fs -c 1 /dev/mmcblk0p2

echo "Update root certificates"
update-ca-certificates
echo "Tighten security"
#passwd -l $CONTAINER_USER
#chsh -s /bin/false $CONTAINER_USER

#usermod -a -G sudo securitas
chmod a+x /usr/local/bin/*
chmod ug+x /usr/local/sbin/*
chmod o+x /etc/cron.hourly/*
chmod o+x /etc/cron.daily/*
chmod o+x /etc/cron.weekly/*
chmod a+r /etc/issue
chown bind.bind /etc/bind/named.conf.options
touch /var/log/querylog
chown bind.bind /var/log/querylog
#echo "Pull docker image"
#docker pull SecuritasMachina/docker-headless-securitas-wall:latest --quiet

echo "TODO Restarting system"

#TODO
#Routine to find init line and replace via java
#cron Malware sigs
#Get malware clamav sigs
#Work on admin interface
#finish transparent setup
#chkrootkit

echo "Cleanup"
rm -rf /tmp/src

